# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_path", models.JSONField(verbose_name="推荐路径")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effectiveness",
                    models.FloatField(null=True, verbose_name="路径有效性评分"),
                ),
                (
                    "adjustment_history",
                    models.JSONField(default=list, verbose_name="调整记录"),
                ),
            ],
        ),
    ]
