# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_data", models.JSONField(verbose_name="周报数据")),
                ("visualization_config", models.JSONField(verbose_name="可视化配置")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("week_number", models.PositiveSmallIntegerField(verbose_name="周次")),
            ],
        ),
    ]
