# Generated by Django 5.2.1 on 2025-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=6)),
                ('submission_rate', models.FloatField()),
                ('accuracy_rate', models.FloatField()),
                ('subject', models.CharField(max_length=20)),
                ('assignment_details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': '作业记录',
                'verbose_name_plural': '作业记录',
                'db_table': 'learning_report_assignmentrecord',
            },
        ),
        migrations.CreateModel(
            name='InteractionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interaction_type', models.CharField(choices=[('question', '提问'), ('answer', '回答'), ('discussion', '讨论'), ('group_work', '小组活动')], max_length=20)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '互动记录',
                'verbose_name_plural': '互动记录',
                'db_table': 'learning_report_interactionrecord',
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_duration', models.PositiveIntegerField(help_text='学习时长（分钟）')),
                ('resource_usage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'learning_report_learningrecord',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=6)),
                ('subject', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('wrong_questions', models.JSONField(default=list)),
                ('knowledge_points', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': '测试记录',
                'verbose_name_plural': '测试记录',
                'db_table': 'learning_report_testrecord',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_study_time', models.PositiveIntegerField(default=0)),
                ('avg_submission_rate', models.FloatField(default=0)),
                ('avg_accuracy_rate', models.FloatField(default=0)),
                ('avg_test_score', models.FloatField(default=0)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('subject_performance', models.JSONField(default=dict)),
                ('knowledge_mastery', models.JSONField(default=dict)),
                ('resource_usage_stats', models.JSONField(default=dict)),
                ('performance_analysis', models.TextField(blank=True)),
                ('improvement_suggestions', models.TextField(blank=True)),
                ('next_week_plan', models.TextField(blank=True)),
                ('visualization_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
                'db_table': 'learning_report_weeklyreport',
                'unique_together': {('week',)},
            },
        ),
    ]
