# Generated by Django 5.2.1 on 2025-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='学科')),
                ('knowledge_point', models.CharField(max_length=100, verbose_name='知识点')),
                ('original_question', models.JSONField(verbose_name='原始题目数据')),
                ('student_answer', models.TextField(verbose_name='学生答案')),
                ('self_analysis', models.TextField(blank=True, verbose_name='自我分析')),
                ('diagnosis_result', models.JSONField(verbose_name='诊断结果')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('knowledge_points', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('solution', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
