# Generated by Django 5.2.1 on 2025-05-18 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentrecord',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
