# Generated by Django 5.2.1 on 2025-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_report', '0002_assignmentrecord_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentrecord',
            name='week',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='week',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='week',
            field=models.CharField(max_length=8),
        ),
    ]
