# Generated by Django 5.2.1 on 2025-06-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0001_initial"),
        (
            "learning_report",
            "0003_alter_assignmentrecord_week_alter_testrecord_week_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_time", models.FloatField(help_text="学习时间（小时）")),
                ("progress", models.IntegerField(help_text="学习进度（百分比）")),
                (
                    "learned_new_knowledge",
                    models.BooleanField(help_text="是否学到新知识"),
                ),
                (
                    "overcame_difficulties",
                    models.BooleanField(help_text="是否克服困难"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_reports",
                        to="class_management.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AssignmentRecord",
        ),
        migrations.DeleteModel(
            name="InteractionRecord",
        ),
        migrations.DeleteModel(
            name="LearningRecord",
        ),
        migrations.DeleteModel(
            name="TestRecord",
        ),
        migrations.DeleteModel(
            name="WeeklyReport",
        ),
    ]
