# Generated by Django 5.2 on 2025-05-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="school",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
    ]
