# Generated by Django 5.2.1 on 2025-05-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0001_initial'),
        ('resource_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='提交内容')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, verbose_name='教师反馈')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('ai_review', models.JSONField(default=dict, verbose_name='AI批改分析结果')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('difficulty', models.FloatField(default=1.0, verbose_name='初始难度系数')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('CLOSED', '已关闭')], default='DRAFT', max_length=10)),
                ('ai_analysis', models.JSONField(default=dict, verbose_name='AI难度分析结果')),
                ('attachments', models.ManyToManyField(blank=True, to='resource_library.resource')),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_management.class')),
            ],
        ),
    ]
