# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_content", models.TextField(verbose_name="原始内容参考")),
                ("generated_questions", models.JSONField(verbose_name="生成试题")),
                ("difficulty_level", models.FloatField(verbose_name="难度系数")),
                ("generation_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
