# Generated by Django 5.2.1 on 2025-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_point', models.CharField(max_length=200, verbose_name='知识点')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('fill_in_blank', '填空题'), ('short_answer', '简答题'), ('essay', '论述题')], max_length=20, verbose_name='题型')),
                ('quantity', models.PositiveIntegerField(default=5, verbose_name='题目数量')),
                ('difficulty', models.CharField(choices=[('basic', '基础'), ('intermediate', '中等'), ('advanced', '困难')], max_length=20, verbose_name='难度等级')),
                ('generated_content', models.JSONField(help_text='包含题目、选项、答案的结构化数据', verbose_name='生成内容')),
                ('validation_status', models.BooleanField(default=False, verbose_name='校验状态')),
                ('test_link', models.CharField(blank=True, max_length=100, verbose_name='测试入口')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '生成测试',
                'verbose_name_plural': '生成测试管理',
            },
        ),
    ]
