# Generated by Django 5.2.1 on 2025-05-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.UUIDField(unique=True, verbose_name='作业ID')),
                ('subject', models.CharField(choices=[('math', '数学'), ('chinese', '语文'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('history', '历史'), ('geography', '地理'), ('politics', '政治')], max_length=20, verbose_name='学科')),
                ('grade', models.CharField(choices=[('P3', '小学三年级'), ('P4', '小学四年级'), ('P5', '小学五年级'), ('P6', '小学六年级'), ('J1', '初中一年级'), ('J2', '初中二年级'), ('J3', '初中三年级'), ('H1', '高中一年级'), ('H2', '高中二年级'), ('H3', '高中三年级')], max_length=10, verbose_name='年级')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_content', models.TextField(verbose_name='作业内容')),
                ('learning_objectives', models.TextField(verbose_name='学习目标')),
                ('student_performance', models.JSONField(verbose_name='学生学情数据')),
                ('difficulty_level', models.CharField(choices=[('too_easy', '过于简单'), ('easy', '偏简单'), ('appropriate', '适中'), ('hard', '偏难'), ('too_hard', '过于困难')], max_length=20, verbose_name='难度评级')),
                ('knowledge_coverage', models.JSONField(help_text='包含知识点列表及其难度评估', verbose_name='知识点覆盖')),
                ('thinking_levels', models.JSONField(help_text='布鲁姆分类法各层次占比', verbose_name='思维层次')),
                ('difficulty_adjustment', models.JSONField(help_text='具体的难度调整建议', verbose_name='难度调整建议')),
                ('question_type_suggestions', models.JSONField(help_text='建议增加或调整的题型', verbose_name='题型建议')),
                ('sequence_optimization', models.JSONField(help_text='题目顺序调整建议', verbose_name='顺序优化')),
                ('personalized_suggestions', models.JSONField(help_text='针对不同水平学生的建议', verbose_name='个性化建议')),
                ('visualization_data', models.JSONField(help_text='用于前端展示的图表数据', verbose_name='可视化数据')),
                ('teacher_feedback', models.FloatField(help_text='教师对分析结果的评分(1-5分)', null=True, verbose_name='教师反馈评分')),
                ('feedback_comments', models.TextField(blank=True, help_text='教师的具体反馈意见', verbose_name='反馈意见')),
            ],
            options={
                'verbose_name': '作业难度分析',
                'verbose_name_plural': '作业难度分析记录',
            },
        ),
    ]
