# Generated by Django 5.2.1 on 2025-05-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_difficulty', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `assignment_difficulty_difficultyanalysis` (
                `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                `assignment_id` char(32) NOT NULL UNIQUE,
                `subject` varchar(20) NOT NULL,
                `grade` varchar(10) NOT NULL,
                `created_at` datetime(6) NOT NULL,
                `assignment_content` longtext NOT NULL,
                `learning_objectives` longtext NOT NULL,
                `student_performance` json NOT NULL,
                `difficulty_level` varchar(20) NOT NULL,
                `knowledge_coverage` json NOT NULL,
                `thinking_levels` json NOT NULL,
                `difficulty_adjustment` json NOT NULL,
                `question_type_suggestions` json NOT NULL,
                `sequence_optimization` json NOT NULL,
                `personalized_suggestions` json NOT NULL,
                `visualization_data` json NOT NULL,
                `teacher_feedback` double precision NULL,
                `feedback_comments` longtext NOT NULL
            );
            """,
            "DROP TABLE IF EXISTS `assignment_difficulty_difficultyanalysis`;"
        )
    ]
