# Generated by Django 5.2.1 on 2025-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_difficulty', '0002_auto_20250518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultyanalysis',
            name='grade',
            field=models.CharField(choices=[('P1', '小学一年级'), ('P2', '小学二年级'), ('P3', '小学三年级'), ('P4', '小学四年级'), ('P5', '小学五年级'), ('P6', '小学六年级'), ('J1', '初中一年级'), ('J2', '初中二年级'), ('J3', '初中三年级'), ('H1', '高中一年级'), ('H2', '高中二年级'), ('H3', '高中三年级'), ('U1', '大学一年级'), ('U2', '大学二年级'), ('U3', '大学三年级'), ('U4', '大学四年级'), ('G1', '研究生一年级'), ('G2', '研究生二年级'), ('G3', '研究生三年级')], max_length=10, verbose_name='年级'),
        ),
    ]
