# Generated by Django 5.2.1 on 2025-06-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_management", "0001_initial"),
        (
            "user_management",
            "0002_remove_teacherprofile_user_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("chinese", "语文"),
                            ("math", "数学"),
                            ("english", "英语"),
                            ("physics", "物理"),
                            ("chemistry", "化学"),
                            ("biology", "生物"),
                            ("politics", "政治"),
                            ("history", "历史"),
                            ("geography", "地理"),
                            ("japanese", "日语"),
                            ("korean", "韩语"),
                            ("french", "法语"),
                            ("german", "德语"),
                            ("russian", "俄语"),
                            ("it", "信息技术"),
                            ("music", "音乐"),
                            ("art", "美术"),
                            ("pe", "体育"),
                        ],
                        default="chinese",
                        max_length=20,
                        verbose_name="学科",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("P1", "小学一年级"),
                            ("P2", "小学二年级"),
                            ("P3", "小学三年级"),
                            ("P4", "小学四年级"),
                            ("P5", "小学五年级"),
                            ("P6", "小学六年级"),
                            ("J1", "初中一年级"),
                            ("J2", "初中二年级"),
                            ("J3", "初中三年级"),
                            ("H1", "高中一年级"),
                            ("H2", "高中二年级"),
                            ("H3", "高中三年级"),
                            ("U1", "大学一年级"),
                            ("U2", "大学二年级"),
                            ("U3", "大学三年级"),
                            ("U4", "大学四年级"),
                            ("G1", "研究生一年级"),
                            ("G2", "研究生二年级"),
                            ("G3", "研究生三年级"),
                        ],
                        default="P1",
                        max_length=10,
                        verbose_name="年级",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        default="45分钟",
                        help_text="例如：45分钟、2课时、1.5课时等",
                        max_length=50,
                        verbose_name="课时",
                    ),
                ),
                ("objectives", models.TextField(default="", verbose_name="教学目标")),
                (
                    "key_points",
                    models.TextField(blank=True, default="", verbose_name="重点内容"),
                ),
                (
                    "difficulties",
                    models.TextField(blank=True, default="", verbose_name="教学难点"),
                ),
                (
                    "materials_needed",
                    models.TextField(default="{}", verbose_name="教学材料"),
                ),
                (
                    "teaching_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inspire", "启发式"),
                            ("inquiry", "探究式"),
                            ("lecture", "讲授式"),
                            ("discussion", "讨论式"),
                            ("practice", "实践式"),
                            ("group", "小组合作式"),
                            ("game", "游戏教学式"),
                            ("project", "项目式"),
                            ("case", "案例式"),
                            ("mixed", "混合式"),
                        ],
                        default="lecture",
                        max_length=20,
                        verbose_name="教学方式",
                    ),
                ),
                (
                    "student_profile",
                    models.TextField(blank=True, default="", verbose_name="学生情况"),
                ),
                (
                    "generated_content",
                    models.TextField(default="{}", verbose_name="AI生成内容"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="版本号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="是否为模板"),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lesson_plan_generator.lessonplan",
                    ),
                ),
                (
                    "shared_classes",
                    models.ManyToManyField(
                        blank=True, to="class_management.class", verbose_name="共享班级"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "教案",
                "verbose_name_plural": "教案",
                "ordering": ["-created_at"],
            },
        ),
    ]
