# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_parameters", models.JSONField(verbose_name="生成参数")),
                ("generated_content", models.JSONField(verbose_name="教案内容")),
                ("version", models.CharField(max_length=20, verbose_name="版本号")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="是否作为模板"),
                ),
            ],
        ),
    ]
