# Generated by Django 5.2.1 on 2025-05-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0002_initial'),
        ('lesson_plan_generator', '0002_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='input_parameters',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='difficulties',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='duration',
            field=models.CharField(default='45分钟', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='grade',
            field=models.CharField(choices=[('P5', '小学五年级'), ('J2', '初中二年级'), ('H1', '高中一年级')], default='P5', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='key_points',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='materials_needed',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='objectives',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson_plan_generator.lessonplan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='shared_classes',
            field=models.ManyToManyField(blank=True, to='class_management.class'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='student_profile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(choices=[('math', '数学'), ('chinese', '语文'), ('english', '英语'), ('physics', '物理')], default='math', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='teaching_style',
            field=models.CharField(blank=True, choices=[('inspire', '启发式'), ('inquiry', '探究式'), ('lecture', '讲授式')], default='lecture', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='generated_content',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.userprofile'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
