# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MistakeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_question", models.TextField(verbose_name="原题内容")),
                ("analysis_result", models.JSONField(verbose_name="错题分析")),
                ("diagnosed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
