# Generated by Django 5.2.1 on 2025-06-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "user_management",
            "0002_remove_teacherprofile_user_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MistakeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_question", models.TextField(verbose_name="原题内容")),
                ("analysis_result", models.JSONField(verbose_name="错题分析")),
                ("diagnosed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userprofile",
                    ),
                ),
            ],
        ),
    ]
