# Generated by Django 5.2.1 on 2025-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mistake_diagnosis", "0001_initial"),
        ("resource_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mistakerecord",
            name="suggested_resources",
            field=models.ManyToManyField(to="resource_library.resource"),
        ),
    ]
