# Generated by Django 5.2 on 2025-05-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资源标题")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("PPT", "课件"),
                            ("VIDEO", "视频"),
                            ("DOC", "文档"),
                            ("TEST", "试题"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/%Y/%m/")),
                ("description", models.TextField(blank=True, verbose_name="资源描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="资源标签")),
                (
                    "related_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="class_management.class",
                    ),
                ),
            ],
        ),
    ]
