# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="班级代码"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开班日期")),
                ("schedule", models.JSONField(verbose_name="课程安排表")),
                ("subject", models.CharField(max_length=50, verbose_name="所属学科")),
            ],
            options={
                "verbose_name": "班级管理",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SubjectCurriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="学科名称")),
                (
                    "grade_level",
                    models.CharField(max_length=20, verbose_name="适用学段"),
                ),
                ("content", models.JSONField(verbose_name="课程大纲结构")),
                ("version", models.CharField(max_length=20, verbose_name="版本号")),
            ],
        ),
    ]
