# Generated by Django 5.2 on 2025-05-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_management", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_classes",
                to="user_management.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_classes",
                to="user_management.userprofile",
            ),
        ),
    ]
