# Generated by Django 5.2 on 2025-05-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("time", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SubjectCurriculum",
        ),
        migrations.AlterModelOptions(
            name="class",
            options={},
        ),
        migrations.RemoveField(
            model_name="class",
            name="code",
        ),
        migrations.RemoveField(
            model_name="class",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="class",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="class",
            name="students",
        ),
        migrations.RemoveField(
            model_name="class",
            name="teacher",
        ),
        migrations.AddField(
            model_name="class",
            name="grade",
            field=models.CharField(default="未设置", max_length=50),
        ),
        migrations.AddField(
            model_name="class",
            name="homework_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="permission_view_scores",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="class",
            name="subject",
            field=models.CharField(default="未设置", max_length=50),
        ),
        migrations.AddField(
            model_name="activity",
            name="class_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="class_management.class",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="class_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="class_management.class",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="participants",
            field=models.ManyToManyField(
                related_name="activities", to="class_management.student"
            ),
        ),
    ]
