# Generated by Django 5.2 on 2025-05-19 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="学号"),
                ),
                (
                    "class_name",
                    models.CharField(
                        default="未分配", max_length=50, verbose_name="班级"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="作业标题")),
                ("description", models.TextField(verbose_name="作业描述")),
                ("due_date", models.DateTimeField(verbose_name="截止日期")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="分数",
                    ),
                ),
                (
                    "submitted",
                    models.BooleanField(default=False, verbose_name="是否已提交"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_performance.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="考试标题")),
                ("exam_date", models.DateTimeField(verbose_name="考试日期")),
                ("duration", models.IntegerField(verbose_name="考试时长(分钟)")),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="总分"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="得分",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("midterm", "期中考试"),
                            ("final", "期末考试"),
                            ("quiz", "小测验"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="考试类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_performance.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
            },
        ),
        migrations.CreateModel(
            name="LearningBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "attendance",
                    models.BooleanField(default=True, verbose_name="出勤情况"),
                ),
                (
                    "participation_score",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="课堂参与度",
                    ),
                ),
                (
                    "homework_completion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="百分比形式，例如：85.5表示85.5%",
                        max_digits=5,
                        verbose_name="作业完成率",
                    ),
                ),
                (
                    "study_time",
                    models.IntegerField(
                        help_text="每天的学习时长", verbose_name="学习时长(分钟)"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="class_performance.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习行为",
                "verbose_name_plural": "学习行为",
                "unique_together": {("student", "date")},
            },
        ),
    ]
